/* eslint-disable @next/next/no-img-element -- dynamic /api/preview route, not optimizable by next/image */
"use client";
import {useState,useEffect} from 'react';
import {ArrowUpRight,ShieldCheck,Mail} from 'lucide-react';
import type {Product} from '@/lib/catalog';
import {CursorArt} from './cursor-art';
export async function send(path:string,data:unknown){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
export function Status({message,error=false}:{message:string;error?:boolean}){return message?<div className={'status-message'+(error?' error':'')} role="status">{message}</div>:null;}
export function SignIn({available,nextPath}:{available:boolean;nextPath:string}){const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(false),[busy,setBusy]=useState(false);return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const d=await send('auth/request',{email,next:nextPath});setMessage(d.message);setError(false);}catch(e){setMessage((e as Error).message);setError(true);}finally{setBusy(false);}}}><label className="field">Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required autoComplete="email" maxLength={254}/></label><p>We’ll email you a secure link to verify your address and sign in. New here? Your account is created when you verify.</p><label className="check"><input type="checkbox" required/> <span>I agree to the <a href="/policies">store policies</a> and understand how my account data is used.</span></label><button className="button primary full-width" disabled={busy||!available}>{busy?'Sending link…':'Email me a sign-in link'}<Mail size={16}/></button>{!available&&<Status message="Store preview: email sign-in is not connected yet."/>}<Status message={message} error={error}/></form>}
export function Verify({token}:{token:string}){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');return <><button className="button primary full-width" disabled={busy||!token} onClick={async()=>{setBusy(true);try{const d=await send('auth/verify',{token});window.location.assign(d.redirect);}catch(e){setMessage((e as Error).message);setBusy(false);}}}>{busy?'Verifying…':'Verify email & continue'}</button><Status message={message} error/></>}
export function Logout(){return <button className="mini-button" onClick={async()=>{try{await send('auth/logout',{});window.location.assign('/');}catch{window.location.assign('/signin');}}}>Sign out</button>}
export function Checkout({p,signedIn}:{p:Product;signedIn:boolean}){const [amount,setAmount]=useState(String(p.price)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestKey]=useState(()=>typeof crypto!=='undefined'?crypto.randomUUID():'');const label=p.mode==='free'?'Add to My Library':p.mode==='donation'?'Donate & get this pack':'Get this cursor pack';return <div>{p.mode==='donation'&&<label className="field">Your donation (IDR)<input type="number" min={p.price} max={100000000} step="1" value={amount} onChange={e=>setAmount(e.target.value)}/><small>A minimum donation of Rp{p.price.toLocaleString('en-US')} is required to unlock this pack.</small></label>}{p.demo?<div className="notice">Sample design — shown to preview the store. This pack is not for sale or download.</div>:<button className="button primary full-width" disabled={busy} onClick={async()=>{if(!signedIn){window.location.assign('/signin?next='+encodeURIComponent('/products/'+p.slug));return;}setBusy(true);setError('');try{const d=await send('checkout',{product_id:p.id,amount:Number(amount),request_key:requestKey||crypto.randomUUID()});window.location.assign(d.redirect);}catch(e){setError((e as Error).message);setBusy(false);}}}>{busy?'Opening checkout…':signedIn?label:'Verify email to '+(p.mode==='free'?'download':p.mode==='donation'?'donate':'buy')}<ArrowUpRight size={18}/></button>}<Status message={error} error/><div className="hero-note"><ShieldCheck size={14}/>{p.mode==='free'?'Free. No payment required.':'Payment confirmation handled securely by Midtrans.'}</div></div>}
export function Preview({p}:{p:Product}){const [dark,setDark]=useState(false);return <div><div className={'product-art detail-art art-'+p.art+(dark?' dark-surface':'')}>{p.preview_key?<img src={'/api/preview/'+p.id} alt={p.title+' preview'}/>:<><div className="art-orbit"/><CursorArt kind={p.art}/></>}</div><div className="preview-controls"><button className={!dark?'active':''} aria-pressed={!dark} onClick={()=>setDark(false)}>Light surface</button><button className={dark?'active':''} aria-pressed={dark} onClick={()=>setDark(true)}>Dark surface</button></div></div>}
export function TrackView({id}:{id:string}){useEffect(()=>{send('views',{id}).catch(()=>{});},[id]);return null;}
export function CheckPayment({id}:{id:string}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div><button className="mini-button" disabled={busy} onClick={async()=>{setBusy(true);try{await send('orders/refresh',{id});window.location.reload();}catch(e){setMessage((e as Error).message);setBusy(false);}}}>{busy?'Checking…':'Check payment'}</button><Status message={message} error/></div>}
