/* eslint-disable @next/next/no-img-element -- dynamic /api/preview route, not optimizable by next/image */
"use client";
import {useMemo,useState} from 'react';
import {Search,ArrowUpRight,ArrowRight,SlidersHorizontal,MousePointer2,ShieldCheck,Download,Heart} from 'lucide-react';
import type {Product} from '@/lib/catalog';
import {CursorArt,Arrow} from './cursor-art';
const money=(v:number)=>'Rp'+new Intl.NumberFormat('en-US').format(v);
export function ProductCard({p}:{p:Product}){return <a className="product-card" href={'/products/'+p.slug}><div className={'product-art art-'+p.art}>{p.preview_key?<img src={'/api/preview/'+p.id} alt={p.title+' cursor preview'} loading="lazy"/>:<><div className="art-orbit"/><CursorArt kind={p.art}/><Arrow className="mini-pointer"/></>}<span className="product-badge">{p.mode==='free'?'FREE PACK':p.mode==='donation'?'SUPPORT A CREATOR':'CURSOR PACK'}</span><span className="card-open"><ArrowUpRight size={18}/></span></div><div className="card-category">{p.category}<span>{p.states} cursors</span></div><h3>{p.title}</h3><div className="card-bottom"><span>by {p.creator}</span><strong>{p.mode==='free'?'Free':(p.mode==='donation'?'From ':'')+money(p.price)}</strong></div></a>}
export function Storefront({products,demo}:{products:Product[];demo:boolean}){
 const [category,setCategory]=useState('All packs'),[query,setQuery]=useState(''),[pricing,setPricing]=useState('all'),[sort,setSort]=useState('featured');
 const shown=useMemo(()=>{const data=products.filter(p=>(category==='All packs'||p.category===category)&&(pricing==='all'||p.mode===pricing)&&`${p.title} ${p.category} ${p.creator}`.toLowerCase().includes(query.toLowerCase()));return sort==='low'?data.sort((a,b)=>a.price-b.price):sort==='high'?data.sort((a,b)=>b.price-a.price):data;},[products,category,query,pricing,sort]);
 return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star" aria-hidden="true">✳</span> SMALL DETAILS. BIG PERSONALITY.</div><h1>Make every<br/>click a little<br/><em>more you.</em><span className="headline-spark" aria-hidden="true">✦</span></h1><p>Thoughtfully made cursor packs for a desktop that feels like home. Find your favorite. Support a creator. Make it yours.</p><div className="hero-actions"><a className="button primary" href="#collection">Find your cursor <ArrowUpRight size={19}/></a><a className="text-link" href="/guide">How it works <ArrowRight size={17}/></a></div><div className="hero-note"><MousePointer2 size={15}/> Made for your everyday clicks.</div></div><div className="hero-scene"><div className="floating-tag top-tag">a little desktop joy <span>✦</span></div><div className="desktop-window"><div className="window-bar"><i/><i/><i/><span>your happy place</span><MousePointer2 size={13}/></div><div className="desktop-canvas"><div className="window-label">LESS DEFAULT.<br/><em>More delightful.</em></div><div className="hero-sticker sticker-matcha"><CursorArt kind="matcha"/></div><div className="hero-sticker sticker-flower"><CursorArt kind="flower"/></div><div className="hero-sticker sticker-ghost"><CursorArt kind="ghost"/></div><div className="hero-sticker sticker-pixel"><CursorArt kind="pixel"/></div><span className="canvas-spark spark-one" aria-hidden="true">✧</span><span className="canvas-spark spark-two" aria-hidden="true">✳</span><div className="desktop-dock" aria-hidden="true"><span>✿</span><span>♡</span><span>✦</span><span>↗</span></div></div></div><div className="floating-tag bottom-tag"><Heart size={16}/> Handcrafted. Full of character.</div><Arrow className="hero-pointer"/></div></section>
 <div className="promise-strip"><span><MousePointer2 size={18}/> A style for every mood</span><span><Heart size={18}/> Independent creativity</span><span><ShieldCheck size={18}/> Payments through Midtrans</span><span><Download size={18}/> Your packs, in one place</span></div>
 <section id="collection" className="collection"><div className="section-heading"><div><div className="eyebrow">THE COLLECTION</div><h2>Your next favorite cursor.</h2></div><p>Little things that make a big difference.</p></div><div className="collection-controls"><div className="tabs" aria-label="Cursor categories">{['All packs','Soft & cozy','Cute characters','Pixel art','Nature','Minimal'].map(c=><button key={c} className={c===category?'active':''} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search-box"><Search size={18}/><input aria-label="Search cursor packs" placeholder="Find your vibe..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="results-bar"><span>{shown.length} {shown.length===1?'pack':'packs'} to make your own {demo&&<span className="sample-label">Sample collection</span>}</span><div><label><SlidersHorizontal size={14}/><select aria-label="Pricing" value={pricing} onChange={e=>setPricing(e.target.value)}><option value="all">All prices</option><option value="free">Free</option><option value="donation">Donation</option><option value="paid">Fixed price</option></select></label><select aria-label="Sort packs" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div></div><div className="product-grid">{shown.map(p=><ProductCard key={p.id} p={p}/>)}</div>{shown.length===0&&<div className="empty-state"><Search size={30}/><h3>No packs found</h3><p>Try another search or category.</p><button className="button secondary" onClick={()=>{setQuery('');setCategory('All packs');setPricing('all');}}>Reset filters</button></div>}</section>
 <section className="how-banner"><div><div className="eyebrow">FROM DISCOVERY TO DESKTOP</div><h2>A fresh look.<br/>Just a few clicks away.</h2><a className="text-link" href="/guide">Your installation guide <ArrowUpRight size={18}/></a></div><div className="steps">{[['01','Find your favorite','Explore free packs, support a creator, or pick a paid collection.'],['02','Make it yours','Verify your email, then claim or complete your payment.'],['03','Give your desktop a little joy','Download from My Library and follow the pack’s instructions.']].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></section><section className="faq"><div><div className="eyebrow">GOOD TO KNOW</div><h2>Little questions,<br/>clear answers.</h2></div><div>{[['What is a custom cursor pack?','A collection of pointer designs that replaces the standard cursors on your desktop. Check each pack’s supported platform, file formats, and included states before downloading.'],['Do I need an account for free packs?','Yes. Verify your email before claiming any pack. Free, donated, and purchased packs then stay together in My Library.'],['How do donation packs work?','Each creator sets a minimum donation. Choose that amount or more to unlock the pack. Donation packs cannot be claimed for Rp0.'],['When can I download my purchase?','Your pack appears in My Library after the server confirms your payment. If confirmation is still processing, use Check payment in your order history.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 </>
}
