import Link from 'next/link';
import {user} from '@/lib/security';
import {sql} from '@/lib/db';
import {Logout,CheckPayment,DeleteAccount} from '@/components/actions';
import {Download,MousePointer2} from 'lucide-react';
export const metadata={title:'My Library',robots:{index:false,follow:false}};
export default async function Dashboard(){const u=await user();if(!u)return <section className="content-page"><div className="eyebrow">MY LIBRARY</div><h1>A home for your favorites.</h1><div className="empty-state"><MousePointer2 size={35}/><h2>Your collection starts here.</h2><p>Sign in with a verified email to find your free packs, purchases, and donations in one place.</p><Link className="button primary" href="/signin">Sign in to My Library ↗</Link></div></section>;
 const packs=await sql(`SELECT p.id,p.title,p.slug,p.version,e.acquired_at FROM entitlements e JOIN products p ON p.id=e.product_id WHERE e.user_id=$1 AND e.active ORDER BY e.acquired_at DESC`,[u.id]);
 const orders=await sql(`SELECT o.id,o.amount,o.status,o.created_at,o.checkout_url,p.title FROM orders o JOIN products p ON p.id=o.product_id WHERE o.user_id=$1 ORDER BY o.created_at DESC LIMIT 100`,[u.id]);
 return <section className="content-page"><div className="dashboard-title"><div><div className="eyebrow">MY LIBRARY</div><h1>Your little collection.</h1><p>{u.email} · Email verified</p></div><div className="order-actions">{u.role!=='user'&&<Link className="button secondary" href="/admin">Creator studio ↗</Link>}<Logout/></div></div>{packs.length?<div className="product-grid">{packs.map(p=><article className="form-card" key={p.id}><Download size={25}/><h2 style={{fontSize:23}}>{p.title}</h2><p className="muted">Version {p.version}</p><a className="button primary" style={{marginTop:18}} href={'/api/download/'+p.id}>Download ZIP <Download size={15}/></a></article>)}</div>:<div className="empty-state"><MousePointer2 size={30}/><h2>A blank canvas, for now.</h2><p>Find a pack you love. Once claimed or paid, it will appear right here.</p><Link className="button primary" href="/#collection">Explore cursors ↗</Link></div>}<h2 className="section-title">Order history</h2><p className="muted" style={{fontSize:12,marginTop:10}}>Payment processing? Check the order below. Downloads unlock after server confirmation.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Pack</th><th>Date</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id}><td>{o.title}</td><td>{new Date(o.created_at).toLocaleDateString('en-GB')}</td><td>Rp{Number(o.amount).toLocaleString('en-US')}</td><td><span className={'badge '+o.status}>{o.status}</span></td><td>{o.status==='pending'&&<div className="order-actions">{o.checkout_url&&<a className="mini-button" href={o.checkout_url}>Continue payment</a>}<CheckPayment id={o.id}/></div>}</td></tr>):<tr><td colSpan={5}>No orders yet.</td></tr>}</tbody></table></div><h2 className="section-title">Account</h2><p className="muted" style={{fontSize:12,marginTop:10}}>You can delete your account at any time. See the <Link href="/policies">store policies</Link> for what is erased and what is retained.</p><div style={{marginTop:14}}><DeleteAccount/></div></section>}
