import Link from 'next/link';
import {redirect,notFound} from 'next/navigation';
import {user,origin} from '@/lib/security';
import {sql,configured} from '@/lib/db';
import {ProductEditor,CreatorForm,SettingsForm} from '@/components/admin-forms';
export const metadata={title:'Creator studio',robots:{index:false,follow:false}};
export default async function Admin({params,searchParams}:{params:Promise<{section?:string[]}>;searchParams:Promise<{edit?:string}>}){
 const section=(await params).section?.[0]||'overview',edit=(await searchParams).edit;const available=configured();const u=await user();if(available&&!u)redirect('/signin');if(available&&!['creator','superadmin'].includes(u?.role))return <section className="content-page empty-state"><h1>Creator access required.</h1><p>Creator accounts are managed by the superadmin.</p><Link className="button secondary" href="/dashboard">My Library</Link></section>;
 const superadmin=!available||u?.role==='superadmin';if(!['overview','products','new','creators','settings','orders'].includes(section))notFound();if(['creators','settings'].includes(section)&&!superadmin)notFound();
 const filter=[u?.id||'00000000-0000-0000-0000-000000000000',superadmin];
 const nav=[['overview','Overview'],['products','My products'],['orders','Sales'],...(superadmin?[['creators','Creators'],['settings','Payments']]:[])];
 let content;
 if(section==='new'||(section==='products'&&edit)){
 let initial;if(edit&&available){if(!/^[0-9a-f-]{36}$/i.test(edit))notFound();[initial]=await sql('SELECT * FROM products WHERE id=$3 AND (owner_id=$1 OR $2)',[...filter,edit]);if(!initial)notFound();}
 content=<ProductEditor initial={initial} available={available}/>;
 }else if(section==='products'){
 const rows=available?await sql('SELECT p.*,u.name creator FROM products p JOIN users u ON u.id=p.owner_id WHERE p.owner_id=$1 OR $2 ORDER BY p.created_at DESC',filter):[];
 content=<><div className="dashboard-title"><h2>Your cursor packs</h2><Link className="button primary" href="/admin/new">Create a pack +</Link></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Pack</th><th>Price</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(p=><tr key={p.id}><td>{p.title}{superadmin&&<small className="muted"> · {p.creator||'Creator'}</small>}</td><td>Rp{p.price.toLocaleString('en-US')}</td><td>{p.mode}</td><td><span className={'badge '+(p.published?'published':'draft')}>{p.published?'Published':'Draft'}</span></td><td><Link className="mini-button" href={'/admin/products?edit='+p.id}>Edit pack</Link></td></tr>):<tr><td colSpan={5}>No products yet. Create your first pack to get started.</td></tr>}</tbody></table></div></>;
 }else if(section==='creators'){
 const rows=available?await sql("SELECT id,email,name,disabled,verified_at FROM users WHERE role='creator' ORDER BY created_at DESC"):[];
 content=<><CreatorForm available={available} initial={rows.find(r=>r.id===edit)}/><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Email</th><th>Account</th><th>Verification</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.disabled?'Disabled':'Active'}</td><td>{r.verified_at?'Verified':'Awaiting verification'}</td><td><Link className="mini-button" href={'/admin/creators?edit='+r.id}>Manage</Link></td></tr>):<tr><td colSpan={5}>No creator accounts yet.</td></tr>}</tbody></table></div></>;
 }else if(section==='settings'){
 const [settings]=available?await sql('SELECT production,enabled,updated_at FROM payment_settings WHERE id=1'):[];
 content=<SettingsForm available={available} initial={settings} webhook={origin()+'/api/payments/webhook'}/>;
 }else if(section==='orders'){
 const rows=available?await sql(`SELECT o.id,o.amount,o.status,o.created_at,p.title,u.name creator FROM orders o JOIN products p ON p.id=o.product_id JOIN users u ON u.id=o.creator_id WHERE o.creator_id=$1 OR $2 ORDER BY o.created_at DESC LIMIT 200`,filter):[];
 content=<><h2>Sales & donations</h2><p className="muted" style={{fontSize:12,marginTop:12}}>Latest 200 orders. Gross amounts before Midtrans fees. Creator payouts are handled manually.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Pack</th>{superadmin&&<th>Creator</th>}<th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.id.slice(0,8)}</td><td>{r.title}</td>{superadmin&&<td>{r.creator||'Creator'}</td>}<td>Rp{r.amount.toLocaleString('en-US')}</td><td><span className={'badge '+r.status}>{r.status}</span></td><td>{new Date(r.created_at).toLocaleDateString('en-GB')}</td></tr>):<tr><td colSpan={superadmin?6:5}>No orders yet.</td></tr>}</tbody></table></div></>;
 }else{
 const [metrics]=available?await sql(`SELECT (SELECT count(*) FROM products WHERE owner_id=$1 OR $2) products,(SELECT count(*) FROM product_views v JOIN products p ON p.id=v.product_id WHERE p.owner_id=$1 OR $2) visits,(SELECT count(*) FROM orders WHERE status='paid' AND amount>0 AND (creator_id=$1 OR $2)) sales,(SELECT COALESCE(sum(amount),0) FROM orders WHERE status='paid' AND (creator_id=$1 OR $2)) revenue`,filter):[{products:0,visits:0,sales:0,revenue:0}];
 const performance=available?await sql(`SELECT p.id,p.title,(SELECT count(*) FROM product_views v WHERE v.product_id=p.id) visits,(SELECT count(*) FROM orders o WHERE o.product_id=p.id AND o.status='paid' AND o.amount>0) sales,(SELECT COALESCE(sum(amount),0) FROM orders o WHERE o.product_id=p.id AND o.status='paid') revenue FROM products p WHERE p.owner_id=$1 OR $2 ORDER BY revenue DESC LIMIT 20`,filter):[];
 const daily=available?await sql(`SELECT to_char(d.day,'DD Mon') day,COALESCE(sum(o.amount),0) revenue FROM generate_series(CURRENT_DATE-13,CURRENT_DATE,interval '1 day') d(day) LEFT JOIN orders o ON o.created_at::date=d.day::date AND o.status='paid' AND (o.creator_id=$1 OR $2) GROUP BY d.day ORDER BY d.day`,filter):[];
 const max=Math.max(1,...daily.map(d=>Number(d.revenue)));
 content=<><div className="stat-grid">{[['Gross revenue','Rp'+Number(metrics.revenue).toLocaleString('en-US'),'Paid orders, before fees'],['Paid orders',metrics.sales,'Excludes free claims'],['Product visits',metrics.visits,'Unique visitor / product / day'],['Cursor packs',metrics.products,'Published and draft']].map(([label,value,note])=><div className="stat-card" key={String(label)}><p>{label}</p><strong>{value}</strong><small>{note}</small></div>)}</div><div className="form-card"><h2 style={{fontSize:23}}>Revenue, day by day</h2>{daily.length&&daily.some(d=>Number(d.revenue)>0)?<><div className="chart-bars" role="img" aria-label={'Last 14 days gross revenue: '+daily.map(d=>d.day+' Rp'+d.revenue).join(', ')}>{daily.map(d=><div key={d.day} style={{height:Math.max(2,Number(d.revenue)/max*125)}} title={d.day+': Rp'+d.revenue}/>)}</div><p className="chart-caption">{daily[0].day} — {daily[daily.length-1].day} · IDR · Last 14 days</p></>:<div className="empty-state" style={{marginTop:20,padding:30}}><p>Your first sale starts the story. Revenue will appear here after payment confirmation.</p></div>}</div><h2 className="section-title">Product performance</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Pack</th><th>Visits</th><th>Paid orders</th><th>Gross revenue</th></tr></thead><tbody>{performance.length?performance.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.visits}</td><td>{r.sales}</td><td>Rp{Number(r.revenue).toLocaleString('en-US')}</td></tr>):<tr><td colSpan={4}>Publish a pack to start tracking its visits and sales.</td></tr>}</tbody></table></div><Link className="button primary" href="/admin/new">Create your first pack +</Link></>;
 }
 return <section className="content-page"><div className="dashboard-title"><div><div className="eyebrow">{superadmin?'SUPERADMIN':'CREATOR'} STUDIO</div><h1>A little creativity.<br/>A growing collection.</h1><p>{superadmin?'Manage the store, creators, and payments.':'Your work, your audience, your insights.'}</p></div><Link className="text-link" href="/">View storefront ↗</Link></div>{!available&&<div className="notice">Admin preview — no live data. Saving and payments are disabled until the store is connected. Production access requires a verified creator or superadmin account.</div>}<nav className="dashboard-nav">{nav.map(([key,label])=><Link key={key} className={section===key?'active':''} href={'/admin/'+key}>{label}</Link>)}</nav>{content}</section>
}
